server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    #    user:
    #    password:
    baseline-description: "init"
    baseline-version: 0

